config/routes.rb
Rails.application.routes.draw do
  resources :desempenos

  resources :estudiantes
  get "show_search_estudiante" => "estudiantes#show_search"
  post "search_estudiante" => "estudiantes#search"

  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/desempeno.rb
class Desempeno < ApplicationRecord
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
	has_many 		:Desempeno
	belongs_to	:grupo
	has_one			:grado, through: :grupo

	def nombre_completo
		"#{nombres.titleize} #{apellidos.titleize}"
	end
end

app/models/grado.rb
class Grado < ApplicationRecord
	has_many       :grupos
  has_many       :estudiantes, through: :grupos
end

app/models/grupo.rb
class Grupo < ApplicationRecord
	has_many       :estudiantes
  belongs_to     :grado
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @desempenos = Desempeno.paginate(page: params[:page], per_page:10)
    @estudiantes = Estudiante.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/desempenos_controller.rb
class DesempenosController < ApplicationController

  def index
    @desempenos = Desempeno.paginate(page: params[:page], per_page:10)
  end

  def show
    @desempeno = Desempeno.find(params[:id])
  end

  def new
    @desempeno = Desempeno.new
  end

  def edit
    @desempeno = Desempeno.find(params[:id])
  end

  def create
    desempeno = Desempeno.create(form_params)
    if desempeno.persisted?
      flash[:notice] = "Desempeño creado exitosamente"
      redirect_to root_path()
    else
      flash[:alert] = "Desempeño no creado, #{desempeno.errors.full_messages}"
      redirect_to new_desempeno_path()
    end
  end

  def update
    desempeno = Desempeno.update(form_params)
    flash[:notice] = "Desempeño actualizado exitosamente"
    redirect_to root_path()
  end

  def destroy
    desempeno = Desempeno.find(params[:id])
    if desempeno.destroy
      flash[:notice] = "Desempeño borrado exitosamente"
    else
      flash[:alert] = "El desempeño no pudo ser borrado"
    end
    redirect_to root_path()
  end

  private
  def form_params
    params.require(:desempeno).permit(:titulo, :descripcion)
  end
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController

  def index
    @desempenos = Desempeno.paginate(page: params[:page], per_page:10)
  end

  def show
    @desempeno = Desempeno.find(params[:id])
  end

  def new
    @desempeno = Desempeno.new
  end

  def edit
    @desempeno = Desempeno.find(params[:id])
  end

  def create
    desempeno = Desempeno.create(form_params)
    if desempeno.persisted?
      flash[:notice] = "Desempeño creado exitosamente"
      redirect_to root_path()
    else
      flash[:alert] = "Desempeño no creado, #{desempeno.errors.full_messages}"
      redirect_to new_desempeno_path()
    end
  end

  def update
    desempeno = Desempeno.update(form_params)
    flash[:notice] = "Desempeño actualizado exitosamente"
    redirect_to root_path()
  end

  def destroy
    desempeno = Desempeno.find(params[:id])
    if desempeno.destroy
      flash[:notice] = "Desempeño borrado exitosamente"
    else
      flash[:alert] = "El desempeño no pudo ser borrado"
    end
    redirect_to root_path()
  end

  def show_search
    @estudiantes = Estudiante.all.paginate(page: params[:page], per_page: 10)
    @grado_collection = Grado.pluck(:nombre, :id)
    @grupo_collection = Grupo.pluck(:nombre, :id)
  end

  def search
    @estudiantes = Estudiante.joins(:grupo, :grado).where(grupos: {id: search_params[:grupo_id]}, grados: {id: search_params[:grado_id]})
    respond_to do |format|
      format.js
    end
  end

  private
  def form_params
    params.require(:desempeno).permit(:titulo, :descripcion)
  end

  def search_params
    params.require(:search).permit(:grupo_id, :grado_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configurar_desempenos_helper.rb
module ConfigurarDesempenosHelper
end

app/helpers/prueba_helper.rb
module PruebaHelper
end

app/helpers/registro_calificaciones_helper.rb
module RegistroCalificacionesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.haml
%h1 Configuración de Desempeños

= link_to "Nuevo" , new_desempeno_path()

%table.table.table-bordered
  %tr
    %th Titulo
    %th Descripcion
    %th{:colspan => "3"} Acciones
  - @desempenos.each do |desempeno|
    %tr
      %td= desempeno.titulo
      %td= desempeno.descripcion
      %td= button_to "Detalles" , desempeno_path(desempeno), method: :get, class: "btn btn-default"
      %td= button_to "Editar" , edit_desempeno_path(desempeno), method: :get, class: "btn btn-default"
      %td= button_to "Eliminar" , desempeno_path(desempeno), :method => "delete", class: "btn btn-default", data: { confirm: 'Are you sure?' }
%h5{:style => "text-align: center"}= will_paginate (@desempenos)

%h1 Configuración de Estudiantes
= link_to "Nuevo" , new_estudiante_path()
= link_to "Buscar", show_search_estudiante_path()

%table.table.table-bordered
  %tr
    %th Nombre
    %th Faltas
    %th{:colspan => "3"} Acciones
  - @estudiantes.each do |estudiante|
    %tr
      %td= estudiante.nombre_completo
      %td= estudiante.faltas
      %td= button_to "Detalles" , estudiante_path(estudiante), method: :get, class: "btn btn-default"
      %td= button_to "Editar" , edit_estudiante_path(estudiante), method: :get, class: "btn btn-default"
      %td= button_to "Eliminar" , estudiante_path(estudiante), :method => "delete", class: "btn btn-default", data: { confirm: 'Are you sure?' }
%h5{:style => "text-align: center"}= will_paginate (@estudiantes)

app/views/desempenos/_form.html.haml
= link_to "Atrás", root_path

= simple_form_for @desempeno do |f|
  .form-group
    = f.input :titulo, label: "Título", input_html: {class: "form-control"}
  .form-group
    = f.input :descripcion, as: :text, label: "Descripción", input_html: {class: "form-control"}
  = f.button :submit, class: "btn btn-primary"

app/views/desempenos/edit.html.haml
%h1 Actualizar desempeño

= render partial: "form"

app/views/desempenos/index.html.haml
%h1 Configuración de Desempeños

= link_to "Nuevo" , new_desempeno_path()

%table.table.table-bordered
  %tr
    %th Titulo
    %th Descripcion
    %th{:colspan => "3"} Acciones
  - @desempenos.each do |desempeno|
    %tr
      %td= desempeno.titulo
      %td= desempeno.descripcion
      %td= button_to "Detalles" , desempeno_path(desempeno), method: :get, class: "btn btn-default"
      %td= button_to "Editar" , edit_desempeno_path(desempeno), method: :get, class: "btn btn-default"
      %td= button_to "Eliminar" , desempeno_path(desempeno), :method => "delete", class: "btn btn-default", data: { confirm: 'Are you sure?' }
%h5{:style => "text-align: center"}= will_paginate (@desempenos)

app/views/desempenos/new.html.haml
%h1 Nuevo desempeño

= render partial: "form"

app/views/desempenos/show.html.haml
= link_to 'Atrás', root_path()
%br
%br
%p
  %strong Código:
  = @desempeno.id
%p
  %strong Título:
  = @desempeno.titulo
%p
  %strong Descripción:
  = @desempeno.descripcion

app/views/estudiantes/search.js.erb
table = $('#table');
$('#table > tbody').empty();
<% @estudiantes.each do |estudiante| %>
  // var markup = "<tr><td><%= estudiante.nombre_completo%></td><td><%= estudiante.grupo.nombre%></td><td><%= estudiante.grado.nombre%></td><td><%= estudiante.faltas%></td><td><%= button_to "Detalles" , estudiante_path(estudiante), method: :get, class: "btn btn-default"%></td><td><%= button_to "Editar" , edit_estudiante_path(estudiante), method: :get, class: "btn btn-default"%></td><td><%= button_to "Eliminar" , estudiante_path(estudiante), :method => "delete", class: "btn btn-default", data: { confirm: 'Are you sure?' }%></td></tr>";
  var markup = "<tr><td><%= estudiante.nombre_completo%></td><td><%= estudiante.grupo.nombre%></td><td><%= estudiante.grado.nombre%></td><td><%= estudiante.faltas%></td></tr>";
  $('#table').append(markup);
<% end %>

app/views/estudiantes/show_search.html.haml
%h2 Buscar estudiantes

= simple_form_for :search, url: search_estudiante_path(), remote: true do |f|
  = f.input :grupo_id, as: :select, collection: @grupo_collection, include_blank: false, input_label: "Grupo"
  = f.input :grado_id, as: :select, collection: @grado_collection, include_blank: false, input_label: "Grado"
  = f.button :submit, value: "Buscar"

%table.table.table-bordered#table
  %thead
    %th Nombre
    %th Grupo
    %th Grado
    %th Faltas
  %tbody
  - @estudiantes.each do |estudiante|
    %tr
      %td= estudiante.nombre_completo
      %td= estudiante.grupo.nombre
      %td= estudiante.grado.nombre
      %td= estudiante.faltas
%h5{:style => "text-align: center"}= will_paginate (@estudiantes)

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Brand
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "#"} Link
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Dropdown
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li
              %a{:href => "#"} Separated link
            %li.divider
            %li
              %a{:href => "#"} One more separated link
      %form.navbar-form.navbar-left{:role => "search"}
        .form-group
          %input.form-control{:placeholder => "Search", :type => "text"}/
        %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Dropdown
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li
              %a{:href => "#"} Separated link
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ProyectoColegio
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: "layouts/navbar"
    - if flash[:notice]
      .alert.alert-success.alert-dismissable
        = link_to "x", "#", class: "close", title: "close", data: {dismiss: "alert"}
        = flash[:notice]
    - if flash[:alert]
      .alert.alert-danger.alert-dismissable
        = link_to "x", "#", class: "close", title: "close", data: {dismiss: "alert"}
        = flash[:alert]
    .container
      = yield